### ISSUE TITLE
Server communication

### ISSUE THREAD

**Issue by nnnik** [SpaceWalkerRS/redstone-multimeter-fabric#1]
Doing the mods server/client communication via mixins means that it is incompatible with every mod doing the same thing.
This includes small mods such as the fabric API, Servux, Multiconnect etc.
fabric-carpet has a way of doing this that isnt prone to breaking.

**Comment by SpaceWalkerRS** [comment]
The networking code was designed with that in mind. It uses the custom payload packets and its own channel, which makes it very unlikely to break unless another mod happens to be using the same channel. I tested compatibility with several other mods, like the Fabric API, G4mespeed, and Carpet, and there are no issues whatsoever.

**Comment by nnnik** [comment]
Hmm yeah you are right.
I initially thought this was the cause as to why the mod didnt work on our server.
After recreating the setup on a local server it ran perfectly fine.
I will recreate the local setup to the remote server again and see if that fixes it.

Nonetheless you will be incompatible with multiconnect (At least you should be)
As the mod grabs all inbound CustomPayload packets on the client and redistributes them using its own API.
If thats something you care about is something you have to know.

**Comment by SpaceWalkerRS** [comment]
Looking at Multiconnect's code, it looks to be as though it also only listens to specific channels. So that shouldn't lead to any compatibility issues.
