### ISSUE TITLE
[Suggestion] Tutorial skipping option for 1.8

### ISSUE THREAD

**Issue by Kikugie** [SpaceWalkerRS/redstone-multimeter-fabric#10]
Some players might've used mod for a while and know how it works. So for tutorial my suggestion is to make it disappear if player doesn't follow it for a few minutes or so.

**Comment by SpaceWalkerRS** [comment]
I think this is a decent suggestion. Expect a 1.8.1 update soon :)

> Completing pop-up explaining how to step ticks and scroll requires opening the meter screen, which is explained two pop-ups later.

While you can hide the HUD, it is hidden not by default, so the pause and scroll HUD actions are relevant even without the Multimeter screen. In fact, the mod is very usable without using that screen at all, though it is needed for meter controls or if you wish to see detailed information about an event. 

> Pop-up explaining the meter controls screen appears after one telling to remove a meter.

Yes, I see how that could be problematic. To be fair though the Multimeter screen will tell you to add a meter if your current meter group is empty. But perhaps re-ordering that will be less confusing.

**Comment by SpaceWalkerRS** [comment]
> Some players might've used mod for a while and know how it works. So for tutorial my suggestion is to make it disappear if player doesn't follow it for a few minutes or so.

implemented in commit [c225dc2](https://github.com/SpaceWalkerRS/redstone-multimeter-fabric/commit/c225dc22066a61a491a5c0aa110cf8ae59eacc2b)

> Pop-up explaining the meter controls screen appears after one telling to remove a meter.

fixed in commit [05d2fbb](https://github.com/SpaceWalkerRS/redstone-multimeter-fabric/commit/05d2fbb7d1c69641dbfebce42beee05fb77d57fe)

I'll keep this issue open until a new release is out
