### ISSUE TITLE
Tutorial pop-up unassigned keybindings and Amecs incompatibility

### ISSUE THREAD

**Issue by Kikugie** [SpaceWalkerRS/redstone-multimeter-fabric#11]
If before completing the tutorial player unassigns some keybindings they will appear as - in the pop-ups.
Also keybindings display doesn't support Amecs modifiers.

**Comment by SpaceWalkerRS** [comment]
This should really be two separate issues, but I'm not sure what can be done about the first. The only reasonable thing I can come up with is that a tutorial step should be skipped if it concerns a keybind that is unbound.

Regarding the Amecs modifiers, is it [this mod](https://www.curseforge.com/minecraft/mc-mods/amecs) you are talking about? If so, I can look into fixing compatibility with it.

**Comment by Kikugie** [comment]
Yep

**Comment by SpaceWalkerRS** [comment]
implemented in commit [3fdf333](https://github.com/SpaceWalkerRS/redstone-multimeter-fabric/commit/3fdf333d0b9d5ddf3aed0397cc5671b521824332)

I'll keep this issue open until a new release is out
