### ISSUE TITLE
Can't dismiss the notificaton saying "Join A Meter Group"

### ISSUE THREAD

**Issue by T3sT3ro** [SpaceWalkerRS/redstone-multimeter-fabric#14]
The notification to use command to join a meter group doesn't want to disappear ~~no matter what I do~~ when trying to join group named with my nick, if I already was in that group. It even stays floating on other screens.

![image](https://user-images.githubusercontent.com/5300963/220888505-6980a8c7-672a-41b3-8ad0-9f0fce257782.png)

I'm using it on 1.18.2 for now on version 1.11.0 of the mod.

**@EDIT**
When trying to join existing meter group (named after my nick) the tutorial step didn't activate. Only when I joined new meter group the step completed.

**Comment by SpaceWalkerRS** [comment]
I suppose there's two different bugs here. 
1. The tutorial step only checks if you successfully joined a meter group, rather than if you used the appropriate command.
2. The toast isn't hidden when you open the menu.

**Comment by SpaceWalkerRS** [comment]
Issue 1. is fixed, issue 2. appears to be an issue with all toasts, not just RSMM's toasts, so I won't consider it an RSMM bug. I'll release v1.11.1 with the fix shortly!
