### ISSUE TITLE
Toast texture glitch

### ISSUE THREAD

**Issue by octanervoc** [SpaceWalkerRS/redstone-multimeter-fabric#15]
# Specifications

```
OS: Linux Mint 20.3

Java ver.: OpenJDK 17.0.9

CPU:       Topology: Dual Core model: Intel Core i5-3230M bits: 64 type: MT MCP arch: Ivy Bridge 
           rev: 9 L2 cache: 3072 KiB 
           flags: avx lm nx pae sse sse2 sse3 sse4_1 sse4_2 ssse3 vmx bogomips: 20753 
           Speed: 2993 MHz min/max: 1200/3200 MHz Core speeds (MHz): 1: 2993 2: 2993 3: 2998 
           4: 3041 

Graphics:  Device-1: Intel 3rd Gen Core processor Graphics vendor: Acer Incorporated ALI 
           driver: i915 v: kernel bus ID: 00:02.0 chip ID: 8086:0166 
           Display: x11 server: X.Org 1.20.13 driver: modesetting unloaded: fbdev,vesa 
           alternate: i915 compositor: compton resolution: 1366x768~60Hz 
           OpenGL: renderer: Mesa DRI Intel HD Graphics 4000 (IVB GT2) v: 4.2 Mesa 21.2.6 
           compat-v: 3.0 direct render: Yes 
```

# Description

Toasts are glitched in MC versions 1.20, 1.20.1, 1.20.2 and 1.20.4. Other versions were not tested and might have the same issue. It is more critical on 1.20.2+.

## MC 1.16.5:

Mod versions tested: all between 1.8.0 and 1.13.1, **inclusive**. All have toasts in good condition.
![2023-12-16_15 42 59](https://github.com/SpaceWalkerRS/redstone-multimeter-fabric/assets/98230395/d29c1f63-279c-4ae8-a0a7-5a52448f3dd8)

## MC 1.20 and 1.20.1:

Mod versions tested: 1.12.0 and 1.13.0. Toasts from the mod have font rendering issues. None are present in vanilla toasts.

![2023-12-16_16 26 45](https://github.com/SpaceWalkerRS/redstone-multimeter-fabric/assets/98230395/6f65bbe1-7811-491f-b430-05cf94bff251)

![2023-12-16_16 26 55](https://github.com/SpaceWalkerRS/redstone-multimeter-fabric/assets/98230395/ed0901f4-7181-41ac-bef9-ddaa29ab9eb8)

## MC 1.20.2+:

Mod versions tested: 1.13.0. Toasts are unreadable.

![2023-12-16_16 49 44](https://github.com/SpaceWalkerRS/redstone-multimeter-fabric/assets/98230395/a561db04-4a35-4206-bfe2-c6f45140a943)

**Comment by SpaceWalkerRS** [comment]
Thanks for the report. I can reproduce the issue, though it looks to be two separate bugs:
- Text rendering in tutorial toasts in 1.20+ - I haven't identified the cause for this yet, but I'm hoping it'll turn out to be a simple one-line fix - we'll see.
- Background image rendering in tutorial toasts in 1.20.2+ - this appears to be related to the GUI texture changes (they split all atlases into separate sprites, similar to how they split `terrain.png` into separate sprites for each block back in 1.5) - this feels like it should be a simple fix but it's going me some head aches.

**Comment by SpaceWalkerRS** [comment]
I think I managed to fix both issues - I'll push out a new release in the next few days.
