### ISSUE TITLE
Hotkeys not being saved

### ISSUE THREAD

**Issue by nnnik** [SpaceWalkerRS/redstone-multimeter-fabric#2]
On my local setup the mod does not save hotkeys after changing them.
This is especially annoying since it shares a key with liteatica.

**Comment by SpaceWalkerRS** [comment]
Which version of the mod are you using? It was supposed to be fixed in 1.1.

**Comment by nnnik** [comment]
I downloaded the latest version from Modrinth.
Hmm yeah I ended up with that Version somehow.

**Comment by nnnik** [comment]
Yeah no what I meant is that I ended up with the outdated version somehow.
Sorry for the confusion - also an update to fabric seemed to fix our issues on our second cmp.

**Comment by SpaceWalkerRS** [comment]
As per v1.4.0 hotkeys are stored in `/.minecraft/config/redstone_multimeter/hotkeys.txt` which makes sure they are saved even when the game is launched without the mod installed. That means this issue is *finally* properly fixed.
