### ISSUE TITLE
Add way to skip the tutorial

### ISSUE THREAD

**Issue by HEIlZMaker** [SpaceWalkerRS/redstone-multimeter-fabric#22]
I love Rsmm, but I do not want to redo the annoying tutorial every time I make a new instance. please add a way to skip it. Thank you

Im new to github, I dont know if this is how you make feature requests, again: Thank you guys for your time and your effort with the mod. I really love it and I know many people don't consider a version ready to update to until rsmm is on that version

**Comment by SpaceWalkerRS** [comment]
If you do not interact with it for a few minutes, I'll go away by itself - see #10
