### ISSUE TITLE
Feature Request: Save Meters between sessions and display meter names

### ISSUE THREAD

**Issue by MagboneD** [SpaceWalkerRS/redstone-multimeter-fabric#23]
This is one of the most useful mods I've ever seen. It's helped me immensely with understanding redstone timing. Ability to print log to file is amazing. 

Is there any way to save all meters and reload between game sessions? It would help a lot when I have to step away from the game for a while in the middle of a complicated redstone build. I'd like to be able to give all meters meaningful names and custom settings and have those readily available when I come back to the build after a few months. 

It would also be really helpful if the meter name was visible in the game window, and not just a colored box. 

Thanks for the awesome work!

**Comment by SpaceWalkerRS** [comment]
> Is there any way to save all meters and reload between game sessions?

There is no such feature in RSMM at the moment, but I like the idea! I see two ways this could work:
- Your meter group is saved server-side, similar to your inventory. It is saved when you leave and will load when you join again. Storing them server-side means you have a unique meter list for each world/server and you will not be able to load a meter list from one world on another.
- Your meter group is saved client-side, similar to the creative-mode saved hotbars feature. You can save and load them manually on any world or server, but they do not do automatically.

I'll be interested to hear your thoughts on these ideas, and if one of them matches what you had in mind.

**Comment by MagboneD** [comment]
I don't know about other users, but I see the client-side saves as the most useful. Especially if you have multiple large, technical builds (like I do), but you have to leave the game for long periods (also me). 

Being able to specific a meter group for a particular build and turn it on/off at will seems like the most scalable, long-term solution, even if it involves the additional step of manually loading the group on each game session.

**Comment by SpaceWalkerRS** [comment]
The first Beta with this feature is out for 1.21! You can check it out on the release page [here](https://github.com/SpaceWalkerRS/redstone-multimeter-fabric/releases/tag/v1.15-beta.1).

**Comment by MagboneD** [comment]
Thanks for the quick turnaround!

I can't test this, however. MC crashes on start. I only have fabric api 0.102 and this mod installed. 

Crash Report attached
[crash-2024-09-04_14.26.37-client.txt](https://github.com/user-attachments/files/16881165/crash-2024-09-04_14.26.37-client.txt)

**Comment by SpaceWalkerRS** [comment]
thanks for testing, I pushed Beta 2 to fix this

**Comment by MagboneD** [comment]
NP. Thanks. I'll let you know what I find.

**Comment by SpaceWalkerRS** [comment]
Alright, probably the last Beta for this update unless there are issues to fix, [here is Beta 4](https://github.com/SpaceWalkerRS/redstone-multimeter-fabric/releases/tag/v1.15-beta.4), which also adds the meter name tags feature you suggested :)

**Comment by MagboneD** [comment]
Rendering the meter names works great. But I'm not getting any response to pressing the keybinds for save/load meter groups.

**Comment by SpaceWalkerRS** [comment]
where/when would this tooltip pop up?

**Comment by MagboneD** [comment]
That's perfect! Thank you!

**Comment by SpaceWalkerRS** [comment]
With both features implemented and 1.15 released, I'll close this issue as *completed*.
