### ISSUE TITLE
scrolling timeline is unresponsive

### ISSUE THREAD

**Issue by T3sT3ro** [SpaceWalkerRS/redstone-multimeter-fabric#3]
First, let me say - great job for bringing this to 1.16.5 and fabric. Now to the core of the problem.

Holding keys for scrolling timeline (`<`, `>`) buffers events for scrolling, so when user releases after some time, the timeline scrolls for some time after that. This lag makes me often scroll too much, because I release the button at exact tick on graph I want to stop scrolling.

**Comment by SpaceWalkerRS** [comment]
Thanks! I just pushed a fix for this issue. I never caught it since it seems to be happening on Windows only. The bug will be fixed in the 1.3 update :)
