### ISSUE TITLE
[suggestion] assign meters default names from components that occupy the spot

### ISSUE THREAD

**Issue by T3sT3ro** [SpaceWalkerRS/redstone-multimeter-fabric#4]
Give default names to meters from components they measure: "comparator 1", "dust 7", "torch 2" etc.

**Comment by SpaceWalkerRS** [comment]
This is a good suggestion! Depending on the exact implementation, it could be very easy as well. If you want to count up the number of comparators, torches, etc. separately, it'll be a little trickier to implement, but I'll give it a go and see what happens.
