### ISSUE TITLE
Make it clientside

### ISSUE THREAD

**Issue by retstonemaster** [SpaceWalkerRS/redstone-multimeter-fabric#7]

**Comment by SpaceWalkerRS** [comment]
Making the mod client-side only is not feasible. There are two major road blocks that prevent this.
- There is no way to get information about events like block updates, shape updates, random ticks, and more.
- And the bigger issue: there is no way to get accurate information about the time and order of events. This would make the mod pretty much useless as a redstone debugging tool.
